# Model
model_name: STDNet
layers: 34
# Dataset
dataset:
    name: "KITTI"
    data_folder: "/opt/data/private/kitti_all"
    input_mode: "gd"
    jitter: 0.1
    calib_path: "./utils/calib_cam_to_cam.txt"


# Optimizer
optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.0


# Training related
epochs: 21
start_epoch: 0
resume: None
train_mode: dense
pretrained: None
# Val mode
val: select
# Important setting####
evaluate: None
# for test: evaluate: bestmodel.pdparams
#######################
rank_metric: rmse


# Others
workers: 4
batch_size: 2
print_freq : 10
